config/routes.rb
Rails.application.routes.draw do
  root 'pages#Home'
  get 'pages/page'
  get 'pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Home
  end
  def about
  end

  def page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=link_to "Home page", root_path %>
    <%=link_to "About us", pages_about_path %>
    <%=link_to "Content", pages_about_path %>
    <%=link_to "Contacts", pages_about_path %>
    <%=

    yield %>
  </body>
</html>

app/views/pages/Home.html.erb
<h1>Home Page</h1>
<p>My new project Ruby on Rails<br>

</p>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>My new project Ruby on Rails</p>

app/views/pages/page.html.erb
<h1>Pages#page</h1>
<p>Find me in app/views/pages/page.html.erb</p>